spring:
  profiles:
    active: dev
  application:
    name: mikufans-lib
  data:
    mongodb:
      uri: mongodb://localhost/test
      auto-index-creation: true
logging:
  level:
    root: info
    org.mikufans: debug
    org.springframework.data.mongodb: debug
  file:
    name: ./log/mikufans-librarians-lib.log
  logback:
    rolling policy:
      max-file-size: 5MB
server:
  port: 45279
