spring:
  profiles:
    active: dev
  application:
    name: mikufans-lib
  data:
    mongodb:
      uri: mongodb://localhost/test
logging:
  level:
    root: info
    org.mikufans: debug
server:
  port: 45279
